name = "falconiere-io"
account_id = "dbfe7c5f7462489a8f6bb8b9b3170134"
compatibility_date = "2025-09-06"

workers_dev = false
preview_urls = false

[observability.logs]
enabled = true

[assets]
directory = "./dist"

[env.dev]
custom_domain = true
route = "dev.falconiere.io/*"

[env.prod]
custom_domain = true
route = "falconiere.io/*"
